project:
  type: website

website:
  title: "Ben Harrap"
  favicon: "img/randy.png"
  search: false
  open-graph:
    locale: en_AU
    site-name: "Ben Harrap"
  google-analytics: "UA-447320706"
  navbar:
    right:
      - post.qmd
      - cv.qmd
      - contact.qmd
  
format:
  html:
    grid:
      body-width: 1000px
      sidebar-width: 200px
      margin-width: 300px
    header-includes: |
      <link href=https://fonts.googleapis.com/css2?family=Noto+Sans+Mono:wght@100..900&family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap rel="stylesheet">
      <script data-name="BMC-Widget" data-cfasync="false" src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js" data-id="benharrap" data-description="Support me on Buy me a coffee!" data-message="" data-color="#ffddd6" data-position="Right" data-x_margin="18" data-y_margin="18"></script>
    theme: custom.scss
    monobackgroundcolor: '#ffddd6'