project:
  type: website

website:
  title: "Ben Harrap"
  site-url: "https://benharrap.com"
  favicon: "/img/randy.png"
  search: false
  open-graph:
    image-alt: "A white and fawn greyhound with its tongue poking out, wearing a black cowboy hat and red neckerchief"
    image: "/img/randy.png"
  navbar:
    right:
      - post.qmd
      - publications.qmd
      - cv.qmd
      - contact.qmd
  
format:
  html:
    grid:
      body-width: 1000px
      sidebar-width: 200px
      margin-width: 300px
    header-includes: |
      <link href=https://fonts.googleapis.com/css2?family=Noto+Sans+Mono:wght@100..900&family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap rel="stylesheet">
      <script data-name="BMC-Widget" data-cfasync="false" src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js" data-id="benharrap" data-description="Support me on Buy me a coffee!" data-message="" data-color="#ffddd6" data-position="Right" data-x_margin="18" data-y_margin="18"></script>
      <!-- Google tag (gtag.js) -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-XYMGR0N804"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-XYMGR0N804');
      </script>
    theme: custom.scss
    linestretch: 2
    monobackgroundcolor: '#ffddd6'