---
title: "CV"
toc: true
---

## Skills

::: {.columns .centered}
::: {.column width="30%"}
{{< fa code >}}

**R, SQL, Stata**

R is my preferred language and I’m proficient with SQL and Stata
:::
::: {.column width="5%"}
:::
::: {.column width="30%"}
{{< fa comments >}}

**Consulting**

There are a lot of good questions out there being asked, I like helping figure out how to answer them
:::
::: {.column width="5%"}
:::
::: {.column width="30%"}
{{< fa recycle >}}

**Reproducible research**

From start to finish I like my make sure my reports are reproducible and as automated as possible
:::
:::

::: {.columns .centered}
::: {.column width="30%"}
{{< fa bath >}}

**Data cleaning**

Who doesn’t like taking some dirty data and giving it a good scrub
:::
::: {.column width="5%"}
:::
::: {.column width="30%"}
{{< fa chart-pie >}}

**Data visualisation**

Sure, pictures speak a thousand words, but they might take a thousand lines of code too
:::
::: {.column width="5%"}
:::
::: {.column width="30%"}
{{< fa magnifying-glass >}}

**Googling**

The majority of my R knowledge is self-taught, so I’d say my Google-Fu is pretty good
:::
:::

## Qualifications

::: {.columns .centered}
::: {.column width="30%"}
{{< fa graduation-cap >}}

**Doctor of Philosophy**

The University of Melbourne, 2025

*The Health of Aboriginal Children born in Western Australia in the Context of Out-of-Home Care*
:::
::: {.column width="5%"}
:::
::: {.column width="30%"}
{{< fa graduation-cap >}}

**Master of Biostatistics**

The University of Melbourne, 2018

Electives in survival analysis, modelling longitudinal and correlated data, and survey design and analysis
:::
::: {.column width="5%"}
:::
::: {.column width="30%"}
{{< fa graduation-cap >}}

**Bachelor of Arts (Honours)**

University of Western Australia, 2015

Double major in psychology, minor in anthropology
:::
:::

## Employment

### Biostatistician, Data Manager, Research Fellow

-   Yardhura Walani, Australian National University
    -   October 2024 – Present

My work focuses predominantly on the Mayi Kuwayu Study, where I developed a data cleaning pipeline using R that harmonises the raw paper and online survey data, incorporates results of our data audits, performs a series of data validation steps, derives new variables and survey weights, integrates external data, and outputs cleaned datasets. Using this pipeline, I also report on question performance and missingness to inform our questionnaire redesign process.

I also provide my expertise to multiple other studies and research groups, as well as supervise graduate students and conduct survey methodology research of my own. In my first few months I also took the lead on finishing the study’s operational manual. In doing this, I converted the existing Word draft into a HTML document using Quarto, making the manual more user-friendly, improving the interface, and making the maintenance of documentation easier.

### Quantitative Social Scientist, Research Fellow

-   Centre for Indigenous Policy Research, Australian National University
    -   October 2023 – October 2024

In my short time at CIPR I worked on two major reports. For the first, I examined social and emotional wellbeing for Aboriginal and Torres Strait Islander children and youth in the Longitudinal Study of Indigenous Children (LSIC). Starting with an Aboriginal and Torres Strait Islander theory of social and emotional wellbeing, I used exploratory factor analysis and structural equation modelling to map data items in LSIC to different domains of social and emotional wellbeing.

The second was a technical report commissioned by the Productivity Commission and Coalition of Peaks, where my co-authors and I proposed a more statistically rigorous method for measuring progress toward Closing the Gap targets. The report covered improvements in measuring progress, recommendations for increasing the quality, frequency, and relevance of data collected for these measures, and guidelines on how to communicate probabilistic statements from statistical models in easy to understand ways.

### PhD Candidate

-   Indigenous Health and Epidemiology Group, University of Melbourne
    -   March 2020 – June 2024

Throughout my PhD I translated findings from Aboriginal-led qualitative research and community reference group conversations into questions I could address using linked administrative datasets. This included how contacts by child protective services are clustered within sibling groups, the prevalence and cumulative incidence of mental and neurodevelopmental health conditions, and estimating the effect of placement in out-of-home care on rates of potentially preventable hospitalisations. 

I used a variety of statistical methods, including descriptive statistics, various regression models, survival analysis, and matching methods. All of my research was written in R and RMarkdown, where I created a reproducible pipeline from data cleaning through to multiple journal articles and my final thesis.

### Biostatistician

-   Deakin University
    -   August 2022 – October 2023
-   Grampians Health
    - September 2021 – October 2023

In these two biostatistician roles I acted as the sole statistical expert in clinical research and academic settings. Across these roles I provided study design and statistical oversight for a randomised trials, including sample size calculations, developing statistical analysis plans and randomisation schemes, advising on technical challenges arising, and analysing trial data. I also developed educational materials and delivered seminars for clinicians on the topic of good research practices.

<!-- ### Research assistant -->

<!-- -   Peter Doherty Institute for Infection and Immunity, University of Melbourne -->
<!--     -   September 2019 – January 2023 -->

<!-- As part of the International and Immigrant Health Group I provided data and statistical support to the research team. Major achievements included the development of a REDCap database and provision of on-site research training for local staff for an evaluation of a dietary and lifestyle intervention in a remote Aboriginal community in the Northern Territory, and a systematic review of type 2 diabetes in resettled refugee and asylum seeker populations. -->

<!-- -   Centre for Health Policy, University of Melbourne -->
<!--     -   April 2018 – January 2022 -->

<!-- I supported Emeritus Professor Lesleyanne Hawthorne in the examination of skilled migration to Australia. My work revolved around sourcing data, understanding its complexities, and summarising it to capture quantitative trends in skilled migration to Australia. ABS data products, including the census, were used, as well as administrative data from the Department of Home Affairs, the Australian Health Practitioner Regulation Agency, and the Occupational English Test. We also collaborated with Canadian colleagues to produce a comparison between Australia and Canada's migration programmes. -->

<!-- -   Melbourne Institute, University of Melbourne -->
<!--     -   May 2019 – February 2020 -->

<!-- In this short-term role I prepared the final wave of the Medicine in Australia: Balancing Employment and Life survey for release. This involved data cleaning, consistency checking, and updating the user manual to reflect changes to the survey, a process which was technical and required great attention to detail. I was also the data custodian, managing the secure transfer of data for research purposes. This role was challenging as I inherited a great deal of code with minimal documentation, however I spent the time to understand how it worked, added the necessary updates, and wrote my own documentation for future reference. -->

<!-- ### Biostatistician -->

<!-- -   Melbourne EpiCentre, Royal Melbourne Hospital -->
<!--     -   November 2017 – May 2019 -->

<!-- I worked as a statistical consultant providing support to clinicians engaged in medical research. The consulting process began with meetings to identify the clinicians' specific research questions and how they could be answered with data and statistical techniques, and concluded with the analysis and writing up of results suitable for publication. I also set up a REDCap database for the IMPETUS-D multi-centre randomised clinical trial and managed the integration of existing administrative data into the database. -->

## Volunteering

### Wearer of Many Hats

-   Statistical Society of Australia
    -   December 2018 – Present

Currently I'm the Vice President of the SSA. Since joining back in 2018, I have taken on many different voluntary roles, including:

-   Secretary and then President of the Victorian and Tasmanian Branch
-   Coordinator of the 2021 Early Career and Student Statisticians Conference
-   Committee member and Secretary of the Equity, Diversity, and Inclusion (EDI) committee
-   Committee member of the Reconciliation Action Plan committee
-   Mentor in the SSA's Mentoring Program

Across these roles I coordinated strategic planning, managed teams, maintained relationships with external organisations, surveyed and reported on EDI in the Australian statistics profession, and wrote EDI recommendations for the Society.

## Research supervision

### Current

Doctor of Philosophy — Sedgwick, M., *Understanding the Health and Wellbeing of Aboriginal and Torres Strait Islander Peoples with Disability*.

Master of Applied Epidemiology — Moreton, K., *TBC*.

### Completed

Psychology Honours — Madeley, B., *Intentions and preferences of adults with diabetes toward seeking psychological support*, 2022. 

Psychology Honours — Chhatiawala, A., *Differences in coping self-efficacy between adults with type 1 and type 2 diabetes and the association with emotional-well-being*, 2022.

Master of Medicine — Haussegger, Z., *Sleep and Mental Health in Aboriginal and Torres Strait Islander Young People: A retrospective data analysis*, 2021.

Master of Medicine — Moffroid, H., *‘Next Generation Youth Well-being Study:’ The importance of cultural connectedness for Aboriginal adolescent health and wellbeing.*, 2021.

## Awards

2025 Bruce Lord Award for Excellence in Research Methodology — Australian Association of Social Workers

2023 T-shirt design competition winner — Australian Statistical Conference

2022 President's Award for Leadership in Statistics — Statistical Society of Australia

2021 T-shirt design competition winner — Statistical Society of Australia

## Memberships and Accreditations

Statistical Society of Australia

Accredited Graduate Statistician, Statistical Society of Australia

International Population Data Linkage Network

International Society of Non-Binary Scientists

## Professional Development

### Workshops

#### 2024

Spatial Analysis in R — Australian Consortium for Social and Political Research Incorporated

Working Smarter with Targets presented by Miles McBain — Statistical Society of Australia

#### 2021

A Crash Course in SQL — Statistical Society of Australia

AMSI Winter School for Statistical Data Science — Australian Mathematical Sciences Institute

#### 2020

Data wrangling with R — Statistical Society of Australia

Data visualisation with R — Statistical Society of Australia

Semiparametric regression in R — Statistical Society of Australia

### Conferences

#### 2025

Global Indigenous Data Sovereignty Conference — Attendee

#### 2023

Australian Statistical Conference and Australian Conference on Teaching Statistics — Attendee

Aboriginal and Torres Strait Islander Mathematics Alliance Conference — Attendee

#### 2022

International Population Data Linkage Network Conference — Presenter

#### 2021

9th SNAICC Annual Conference — Attendee

The Early Career and Student Statisticians Conference — Presenter

#### 2020

International Population Data Linkage Network Conference — Attendee

#### 2018

International Metropolis Conference — Presenter

Joint International Society for Clinical Biostatistics and Australian Statistical Conference — Attendee

UseR! Conference Brisbane — Attendee
