---
title: "A big ask: try and take this article seriously"
author: "Ben Harrap"
date: 2023-10-05
categories: ["Academic"]
tags: ["Academic", "Gender"]
---

Like the stench of a garbage bin on a hot summer's day, Alice Sullivan's [article](https://academic.oup.com/jrssig/article/20/1/6/7034186) published in Significance magazine back in February 2023 keeps wafting its shitty smell my direction. I've already spent too much of my time trying to get Significance magazine to do literally anything about this poorly written piece of TERF ideology. Seeing the SSA Twitter account share the article again today reminded me that this article unfortunately exists in a publication I consider to be respectable.

My original complaint I sent through to Significance magazine was diplomatically and academically written, which doesn't seem to have gotten me anywhere. So here we are on my blog and I don't care to tone-police myself. Yes, I'm pissed off. I'm pissed off that Significance magazine *apparently* peer-reviewed this article and still published it, I'm pissed off that the article was acceptable because of "balanced" coverage, and I'm pissed off that Significance magazine maintains this publication given that it flies in the face of the diversity, equity, and inclusion goals of the Royal Statistical Society, American Statistical Association, and Statistical Society of Australia (the three bodies that operate the magazine).

Anyway, below is a less kindly-worded adaptation of the complaint that I originally sent in.

> Sex is a fundamentally important variable in social statistics. And yet, in recent years, data collection on this vital statistic has become controversial.1,2

The claim here is that collecting data on sex is controversial. There's not actually any evidence to support this claim, a common theme throughout the article. The citations are links to more of the author's own works where they state this same opinion without any evidence to support it. The main evidence that the author puts forward is their own bugbear about the fact that openly being a TERF has had consequences and not everybody agrees with them. Their writing style also has this awful air of intellectual superiority, e.g. "I was initially naïve enough to imagine that denial of the material reality and importance of sex would not be enforced in the rational world of social statistics".

> The push against sex-based data collection is a growing trend internationally.

Evidence where? That's a pretty big statement you're making there. I think maybe what you're trying to say is "modern data collection practices are more carefully considering what variables are important and the social experience of one's own gender identity is more relevant for social research than sex".

> Administrative data collection exercises have removed data on sex, sometimes by conflating sex with gender identity (see, for example, the US Census Bureau: bit.ly/3TWbeVp)

This is a good one - rather than the citation not providing evidence, it actually provides evidence directly contradicting the statement! If you take a moment to read the citation, it's clear that the US Census Bureau understands the difference between sex and gender they are continuing to ask a question on sex.

> This has affected data on a wide range of questions, including crime, education, employment and health.

Nope, see the previous point.

> In the UK, sex appears to have become a devolved matter, with practice in Scotland diverging from England and Wales and Northern Ireland. 

More opinion again.

> Attempts to remove sex-based language and sex-based data collection share a common root in queer theory and gender identity activism originating in the USA. This is part of a larger political project aimed at the erasure of sex categories (bit.ly/3i5lFIG).

Time to introduce a spooky conspiracy, who doesn't love a "larger political project"? Pointing fingers at some unnamed but somehow coordinated group of boogeypeople is great for stirring up outrage! Oh wait, there's a citation there. Surprise! More of the author's (and their friends) own opinion, but this time it's in a self-published report funded by [Women's Place](https://en.wikipedia.org/wiki/Woman%27s_Place_UK), an anti-trans organisation. Would it surprise you that research funded by an anti-trans organisation found 'evidence' that supports their ideology?

The report's [website](https://thepoliticalerasureofsex.org) has this lovely claim "... the census authorities ... conflate the concepts of sex and gender identity, confuse what they are measuring...". Unsurprisingly, the Office for National Statistics aren't stupid and don't do anything of the sort. Have a gander at the ONS' [report on the topic](https://www.ons.gov.uk/census/censustransformationprogramme/questiondevelopment/sexandgenderidentityquestiondevelopmentforcensus2021), it's pretty evident they know that sex and gender are different things, but that doesn't fit the narrative.

> A feature of this activism has been calls for “no debate” leading to radical changes in policy and practice, including changes to data collection, being brought in without input from expert and critical voices.3

I think what you mean by "without input from expert and critical voices" is "without input from people who I think are experts who share my political opinions". What's the citation this time? You guessed it! More of the authors own ramblings. This time in an article hilariously titled "The Gender Wars". When you're unironically titling your own academic research this way it's pretty evident how deep down the TERF rabbit-hole you are.

> Sex. In humans, sex is a binary biological category. Individuals are classified by reproductive function as male or female. Sex is determined at conception, and is immutable.6

Nice attempt to define sex, but have you heard of Wikipedia? You might want to give its [article on sex](https://en.wikipedia.org/wiki/Sex) a read before pretending a single biology paper **ON MICE** is good evidence for your definition. I'm no biologist (neither is Sullivan, mind you), but my conclusion from the Wikipedia article is there is no singular definition of sex and it depends entirely on the context being discussed and the intentions of the measurement/classification.

> Gender. The term “gender” refers to the stereotypes and social roles that are associated with each sex. Gender is a social category, rather than an individual one, and refers to how society sees girls and boys and women and men, based on their sex. Gender refers to the hierarchical power structure between men and women.7

Interesting way to work in your belief that gender is binary too. I too like to use articles published a quarter of a century ago to talk about contemporary social issues. Very relevant. Perhaps another [visit to Wikipedia](https://en.wikipedia.org/wiki/Gender) is in order. 

> ... in a recent article for Significance, Thornton et al. cast doubt on the idea that sex is binary, and describe sex as the sum of a set of sexed characteristics.4 They suggest that it is better to ask specifically about these sexed characteristics (for example, “do you have ovaries”?) rather than asking a study participant’s sex.

Thornton et al.'s suggestion to think critically about what you're trying to measure and be nuanced in the questions you ask is the fundamental basis of doing good science. If your research focused on ovaries then it's the most obvious question that you would need to ask participants - do you have ovaries. Not all people who respond 'female' to a question on sex will have ovaries.

As an aside, if you want to know what an article that provides a good, nuanced take on how we should be collecting data on sex and gender identity, read the article that Sullivan is referring to here (https://academic.oup.com/jrssig/article/19/1/40/7029673)

> There are a number of problems with this perspective: first, it neglects the fact that sex has systematic effects on health and social life;

This one's a bizarre take, but leaps into the illogical abyss are commonplace in Sullivan's article. The Thornton et al. article suggests that researchers take the time to think carefully about what information they need to collect. There's nothing in the Thornton article that suggests sex does not have systematic effects on health or social life. 

> second, it leads to language which many people, especially women, may find dehumanising;

I mean this doesn't have to be the case. One of the sections in Thornton et al., in big bold letters, is "Centre inclusivity and respect". On the flip side too, if we adopt Sullivan's perspective that we should only collect binary sex data, how do you think intersex people will feel?

> and third, it leads to questions which are less readily understood and more likely to mislead study participants than a simple question on sex.

At this stage Sullivan really needs to be providing some kind of example here, otherwise she's just asking us to take her at her word. There's not actually any substance behind these arguments though. Of course we can imagine situations where researchers have designed a poorly-worded question or don't collect the right bit of information for their study. I'm sure this happens all the time. While Thornton's article argues for more nuanced data collection practices, it's bizarre that Sullivan argues against this and even more surprising that Significance magazine thought it appropriate to publish this advice.

> This elision of gender and gender identity obscures the social importance of sex. This confusion has led to the claim, from sources including Scotland’s chief statistician (bit.ly/3gtjGNW) and the US National Academy of Sciences, Engineering and Medicine,5 that “gender” should be collected as a default, and sex should only be asked in limited circumstances.

Neither of the citations provided suggest that gender should be collected by default. It'd be nice if Sullivan would actually include a citation that supported the statement it was attached to. Feel free to read the [Scottish government](https://www.gov.scot/publications/data-collection-publication-guidance-sex-gender-identity-trans-status/pages/1/) and [National Academies](https://nap.nationalacademies.org/catalog/26424/measuring-sex-gender-identity-and-sexual-orientation) publications. They both provide nuanced consideration of the distinction between sex, gender, and gender identity. It's shocking that Sullivan manages to cite so many articles that contradict her own ideas, you'd think she hadn't even read them!

Hilariously-but-not, the Scottish government publication actually refers directly to a definition provided by the Royal Statistical Society:

"a social construction relating to a set of norms, roles and relationships that is founded in social mores, laws, processes and policies based on labels of masculinity and femininity. This is time and culture specific;"

which comes full circle back to Significance magazine. It does make me wonder how this article passed editorial review.

> Thornton et al. claim that sex is not binary, and is defined by a constellation of primary and secondary sex attributes.4 Yet how would we know which attributes related to each sex if this was the case? The fact is that sexed attributes do not randomly cluster in individuals, and neither can they be seen as a spectrum.8,9

This one hurt my brain. Sex must be binary because sex attributes aren't random? What? What do you think the process of categorising things involves? We look for patterns in things and group them together. 

> There is a reason why the people with ovaries do not also have testicles, and vice versa.

Frankly this is an offensive statement that denies the existence of intersex people who fit this exact description.

> Humans reproduce sexually, and the two sexes are defined by their roles in sexual reproduction. The claim that more than two sexes exist would imply that there exist additional classes of people, beyond male and female, who play a necessary role in the production of a new human.

You know, things don't magically become true if you keep saying them. Go read Wikipedia. Focusing on people's ability to create children seems like another weird take, what if you can't have children? Does that mean you're not male or female?

> It is because we want to know people’s sex that we ask for this information, rather than some alternative such as “do you have a uterus?” (though of course we might need to know that too in specific medical circumstances).

Ah so the cracks in your shitty argument keep appearing huh? Nice to see you acknowledge that we do need to collect very specific bits of information because accurate measurement is important in particular circumstances.

As an aside, there's a subtle confusion that Sullivan perpetuates throughout her entire article. Whether intentional or not, Sullivan starts out talking about data collection in official statistics like a census, but then switches to talking about research design then to administrative data in a service delivery context. 

These are all *very* different scenarios when it comes to data collection and have their own nuances, treating them as comparable and pretending your arguments in one context are relevant in another is deceptive.

> In a similar vein, Democratic congresswoman Alexandria Ocasio-Cortez responded to the threat to the legal right to abortion in the USA by stating: “The gutting of Roe v Wade imperils every menstruating person in the US.” This desexed language has become prevalent in official information about women’s health (bit.ly/3i5sgCW).

I really wonder how seriously Sullivan takes her arguments or if this is just pearl clutching. Language that refers to pregnant people, or people who menstruate, is being incredibly specific in its use, because it's important to be specific in giving health advice. Not all people who menstruate are women and not all women menstruate, not even all cisgender women menstruate.

> Using plain language which is widely understood, including by people with limited education or English language skills is a basic principle of questionnaire design as well as medical communication.

Yes, making sure your questionnaires are understandable is important, we agree on this.

> To ask, “Do you have ovaries?” instead of “Are you male/female?” as Thornton et al. suggest,4 is likely to lead to error and non-response which will disproportionately affect marginalised groups.

I'm gonna need a big ol' citation for this statement please, otherwise it's just conjecture. You're publishing in a statistics magazine don't you know, we love to hear about error and non-response.

> The population which is likely to be confused by desexed language may be expected to be considerably larger than the population which such language is aimed at, so the damage to data quality may be substantial.

More conjecture. It's conjecture season!

> Proponents of the view that sex is not binary typically invoke people with differences/variations of sexual development (DSDs/VSDs). Yet it is clearly a fallacy to suggest that the existence of a small minority of anomalous cases invalidates the existence or usefulness of a categorical variable.

Oh-ho, dehumanising intersex people again are we? They're just anomalies to be discarded in the pursuit of your binary sex dreams? I think somebody's a hypocrite and your ideology is showing.

> Thornton et al. rightly argue that it is important to be clear in one’s use of terminology, in order to avoid confusion.4 Gender identity is not the same thing as sex. The acknowledgement that these distinct variables cannot be captured accurately in a single item is welcome.

Holy U-turn batman, what was the point of the previous three sections of your article if you're going to throw in a statement that goes against everything you just argued for? 

> It is a basic principle of questionnaire design that a question should not be open to widely different interpretations by different respondents. “Gender” is commonly used to refer to all of the three concepts in the “Definitions” box above: sex, gender and gender identity. Therefore, using “gender” on its own is inevitably unclear, and as such should be avoided in questionnaires.

Yes, I once again agree that questions should be clear and specific. The solution to having a question that might be unclear is to figure out how to make it clear, not to remove it. Bad take.

> In common usage, “gender” is simply a synonym for sex. In fact, as the linguist Deborah Cameron (bit.ly/3ERf51E) points out, people have been using the term “gender” as a fancy term for sex for over 500 years. Some researchers may claim that this use of gender is “wrong”, but good questionnaire design takes its lead from common parlance rather than assuming knowledge of technical or disciplinary usage.

How much more shitty questionnaire design advice can you fit into one article GOOD LORD. “Good questionnaire design” sets participants up with the knowledge required to answer questions accurately, rather than designing questions which are poorly worded or create data which is unclear in what it is measuring. I confuse systolic and diastolic blood pressure but would never suggest that doctors disregard which type of blood pressure we’re talking about.

If only you'd read any of the publications by national statistical agencies that you cite, they are all very clear on the distinctions between sex and gender and why they should be measured jointly. Also, spot the logical fallacy. "This is the way it's always been done" isn't a good argument and you know it.

> As the transgender population has increased rapidly, particularly among youth, those with responsibility for data collection are rightly concerned to gather accurate data on this group. In order to achieve this, we need accurate data on both sex and gender identity. 

Even Sullivan can't keep up the facade that her arguments have any merit. What a waste of everyone's time who had the mental fortitude to get this far through the article. First we had arguments that we should only be collecting sex, now that we need to be collecting sex and gender identity? 

> Collecting useful data on gender identity, at a time when this relatively unfamiliar phenomenon is in rapid flux, is challenging, and requires careful consideration of the intelligibility and meaningfulness of the questions used within the general and gender-diverse populations.

It's not unfamiliar and it is indeed being carefully considered. Do you know how I know that? Because cause of all the citations you were able to point to that demonstrate the work various national statistical agencies are doing on determining the best way to measure these things! Oh the irony.

> Yet relatively little attention has been paid to considering how best to collect data on gender identity.

You're fucking kidding me. Your entire article and all of your citations are about this literal fucking topic, how dense do you think your audience is?

> Instead, gender identity advocates have focused on attempting to deconstruct and erase sex as a category.

Nope, see above and read literally any of the citations of national statistical agencies that you claim to have read (because it's poor academic rigour to cite something without reading it, you know).

> The argument that “gender” rather than sex should be the default variable appears to be based on the premise that sex only matters where there is a direct biological cause of difference - often combined with a refusal to acknowledge the salience of biology even where it is obvious, for example in sports.18

I still don't know who is making this argument, that gender should be a default. Seems like a straw man to me. Also, note again that Sullivan makes these general statements about how people are collecting data. It's certainly not national statistical agencies that are suggesting we only use gender, nor is it the Thornton et al. article. 

Once you realise that Sullivan makes these vague, general statements about these 'genderist' boogeypeople who are forcing everyone to only measure gender, you notice the article is peppered with them. The nefarious bit is how she presents these statements alongside statements about national statistical agencies, as if her vague statements and the choices of national statistical agencies are related and the former somehow constitutes evidence of the latter.

> Gender identity is a distinct concept, and there is no evidence to suggest that gender identity is more important than sex across all the domains that social and health scientists may be interested in (bit.ly/3ABtHQ7).

STRAW MAN BE GONE. Only you have been claiming that other people think "gender identity is more important than sex", nobody is looking for evidence to support that claim because nobody believes it.

> Sex is not a difficult concept. Failure to collect data on sex means that we fail to monitor sexism and to capture sex differences.

I agree with this sentiment, as do all the proponents of collecting high-quality data on sex and gender. This is yet another straw man argument (that we are not collecting data on sex) implying that there is a grand conspiracy to convince governments to cease collecting data on sex. If anything, Sullivan advocates for collecting poor quality data on sex by - at times - stating we should only be asking about sex not collecting gender.

> It is time to call a halt on the erasure of sex in data collection.

Fuck right off. You haven't given a single piece of evidence throughout this entire shitshow of an article that supports this claim, but ending this article with such a grandiose claim is par for the course at this stage.