---
title: "Reflecting on my PhD experience"
author: "Ben Harrap"
date: 2024-08-10
output:
    blogdown::html_page:
      toc: false
categories: ["Academic", "Self"]
tags: ["Academic","PhD","Research","Learning"]
---

I submitted my PhD thesis nearly two months ago, and while I still have to wait for examiner feedback to claim that I've 'finished', I think I've sufficiently decompressed post-submission. This post is basically me reflecting on my experience doing the PhD, although hopefully there's some useful bits for those of you thinking of or currently doing a PhD.

## Being broke

Back in 2018 I finished my master's degree in biostatistics and proceeded to work in various roles applying my statistics and data skills. These were predominantly academic positions, and being employed by an Australian university meant my salary was tied to very specific pay bands. I was happy to be working full-time, having been working weekends and studying full-time for the last year and a half. Going from working a minimum-wage casual retail job to earning a full-time Level A wage felt good by comparison.

I'd wanted to do a PhD for a long time, but now that I was earning a full-time wage my partner and I were able to work toward financial goals. The prospect of being a broke PhD student was not appealing. I didn't necessarily have to be broke though, as I found out after I chatted to a friend of mine who suggested working a couple of days in addition to doing a PhD. I ran the numbers and he was right, if I was able to secure a PhD scholarship (~$30,000 a year tax-free at the time) and work two days a week, my income was almost the same as my current full-time income as a research assistant.

With this in mind, I figured I may as well do a PhD. Graduate researchers are a source of cheap labour and the work would be similar to what I was currently doing. And since the money was practically the same, why not spend the next 3 to 4 years doing the same work and earning the same money, but ending up with a PhD and in turn increasing my earning potential? Well it turns out the work wasn't the same as being a research assistant (there is a LOT more independence), but the pay was at least the same.

At the time however, I wasn't passionate about any area in particular. I just really enjoyed coding and was agnostic to the context that I was doing it. So how does that turn into a PhD?

## Passion vs. job

I've come to the realisation that PhDs tend to fall into one of two categories. You either start a PhD because you're passionate about the area, or you see it as a job where part of the remuneration is you get a qualification at the end. I was certainly in the latter category initially, although my passion for the area developed over the course of my PhD.

Since I didn't know what I wanted to do, I looked for projects being advertised that were suited to my skills in an area that I thought was interesting. I happened across an advert on the Statistical Society of Australia's [job forum](https://statsoc.org.au/forum-job-vacancies){target="_blank"}. I saw an advert for a quantitative PhD student to do research into the health outcomes of Aboriginal children in out-of-home care using linked administrative data. At the time I didn't know much about the area, but I wanted my research to have meaning and 'do good' and the project ticked those boxes.

My relationship with my PhD was certainly to treat it like a job. Besides the last 3 months of 'crunch', I never worked evenings or weekends. I worked 9 to 5, five days a week - three being on my PhD and two being in my job. The advent of covid and remote working was a boon, because it meant I could be a lot more flexible with my time. Some weeks I might work 5 days on my PhD and make up work days at a later date, as long as the work got done nobody minded.

## A time to learn

Coursework degrees are rigid in their structure and having a job means learning typically has to be directly applicable to the work you are doing. The timeframe of a PhD and the environment of learning is unique, so make the most of your time and learn and don't forget that you're a PhD **student**. I learned an enormous amount over the course of my PhD that was ancillary to it.

I could have stuck with Stata and written my thesis in MS Word, but I wanted to learn R so I committed to doing as much as feasibly possible in R and RMarkdown. I could have used statistical methods I had used before, but where possible I made sure to implement methods I hadn't. Try and build opportunities to learn extra skills into your research. 

Also take every opportunity you can to apply for funding to attend conferences, workshops, etc. When you're a student, fees are generally a lot lower, so any funding you can get goes. If you're in the statistics field in Australia, make sure you join the Statistical Society of Australia - membership is very cheap for students and there is often funding on offer to support students to attend events.

## Things that were difficult

There are many difficult parts to doing a PhD, which are usually difficult because you've never done them before. I think it's useful to remember that if something's difficult it probably means you're learning, and that's a good thing. Realising this doesn't make it any less difficult mind you.

### Working on the same thing, for a long time

The most difficult part of the PhD for me was completing my first research article. My assessment at the start was that the code would only take a couple of weeks to write, the write-up might take another month, so budgeting three months to have my first draft ready was being **generous**. In reality, two years passed between the first meeting to discuss the aims of the article and when it was finally published.

My expectations for how long the process would take didn't improve either. For the next article, I still thought three months was a reasonable timeframe. It took nine months from start to submission. The third article took five months from start to submission. With practice and experience, I've certainly became more efficient with my time, but I'm still terrible at estimating how long something will take.

For the longest time, the disconnection between my expectation of how long it *should* take and how long it was actually taking made me feel very stupid. This feeling of stupidity also turned into resentment at times - I didn't want to get feedback from data custodians, I didn't want reviewer comments, I just wanted the research to be done.

### Dealing with feedback

I've gotten much better at separating myself from my work, in that I don't see feedback as a criticism of who I am, I see it as an opportunity to improve my work. I do still feel a whole host of emotions when I receive feedback, because after all I thought the work was good enough to submit for review. My advice for managing feedback is to read the feedback during work hours, but only read it. Do not respond to it, just let your mind dwell on it and return to it the next day. This lets you feel whatever emotions you're going to feel on your initial reading of the feedback and by sleeping on it you'll return to it with a clearer mind and give more measured responses.

### Motivation

I struggled a LOT with motivation. It felt like days or weeks would go by and I hadn't done anything at all. Then I'd have periods of enormous productivity. Unfortunately, being extremely productive in a short period of time doesn't alleviate the guilt experienced during my unproductive periods. I was forever beating myself up for not being able to have productive periods *all the time*. Being diagnosed with ADHD 8 months before I was due to finish wasn't ideal, but better late than never I guess.

Deadlines were a mixed source of motivation. External deadlines were excellent - I'm very good at being accountable to someone else. Things like candidature milestones or submission deadlines were very successful motivators. Setting my own deadlines was not so good, sometimes I'd be able to meet them, but often I'd feel guilty because I wasn't meeting them - a problem exacerbated by my terrible ability to know how long things should take.

### Mental health

If you speak to practically anyone that's done a PhD, they'll tell you that their mental health suffered. This was true for me and living in Victoria during covid lockdowns certainly didn't help. I think my perspective on hardship, that feeling like shit is usually temporary, helped carry me through it all though. I'm not suggesting you change your mentality though ("have you tried just not being depressed?"), so here's some other people/things that also got me through:

- My partner, who supported me in many ways through the whole process
- My greyhound(s), who love their routines and will not let you skip a walk (getting out of the house was good)
- Doing things that made me happy, which at the time were brewing beer, gardening, and playing video games
- Seeing a psychologist

## Should you do a PhD?

Hopefully my experience highlights some of the positives and negatives of doing a PhD. Only you can answer this question though, because the answer is going to depend on what your values and aspirations are.