{
  "hash": "be45701550e8a48d264770706da8a8f4",
  "result": {
    "engine": "knitr",
    "markdown": "---\nformat: html\ntitle: \"Not all missings are created equal\"\nauthor: Ben Harrap\ndate: 2025-07-14\ntoc: false\ncategories: \n  - R\n  - programming\n---\n\nI posted this question on Bluesky the other day, because I wasn't sure whether a row-wise or column-wise solution would perform better for the problem I was trying to solve.\n\n<blockquote class=\"bluesky-embed\" data-bluesky-uri=\"at://did:plc:kk6ztlsaka6mdlpursuwd4yt/app.bsky.feed.post/3ltieznd74c2k\" data-bluesky-cid=\"bafyreig2ngchvmshsw2thsgm5qscnvbvoi6jipcjuki5ee62t3stpi56dy\" data-bluesky-embed-color-mode=\"system\"><p lang=\"en\">Thoughts #rstats?\n\nI&#x27;m updating values in col_n based on values in col_n+1 for every column in a dataframe (say 500 cols), for tens of thousands of rows.\n\nDo you expect doing colwise operations to be faster? Or transposing the data and doing rowwise operations?</p>&mdash; Ben Harrap (<a href=\"https://bsky.app/profile/did:plc:kk6ztlsaka6mdlpursuwd4yt?ref_src=embed\">@bharrap.bsky.social</a>) <a href=\"https://bsky.app/profile/did:plc:kk6ztlsaka6mdlpursuwd4yt/post/3ltieznd74c2k?ref_src=embed\">July 9, 2025 at 8:47 AM</a></blockquote><script async src=\"https://embed.bsky.app/static/embed.js\" charset=\"utf-8\"></script>\n\nThe feedback was consistent in stating that column-wise operations would be faster. So what did I do? I wrote a row-wise solution!\n\nOk hear me out though, there was a good reason and I'll go through the problem and my thinking here, because the problem isn't as simple as I'd laid out in my Bluesky post.\n\n## The problem\n\nPeople do questionnaires (this is not the problem). Some people skip a question or two, some people skip a whole set, and some people get bored and stop half-way. These all lead to missing data, but the pattern of missingness is different and is informative when thinking about designing the next survey wave's questionnaire.\n\nThe problem is how to efficiently identify these types of missingness in the data and code them as such.\n\nLet's start with a data dictionary some example data to help illustrate.\n\n## The data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(gt)\nset.seed(4)\n\nsurvey_data <- tibble(\n  id = c(1, 2, 3, 4, 5),\n  name_first = c(\"Tom\", \"Penny\", \"Trevor\", \"Ursula\", \"Jenny\"),\n  name_last = c(\"Smith\", \"Jones\", NA, \"Smith\", \"Jones\"),\n  age = c(62,52,37,44,NA),\n  x1 = runif(5, 0, 2),\n  x2 = runif(5, 0, 2),\n  x3 = runif(5, 0, 2),\n  x_text = c(\"Lorem\", NA, NA, \"Lorem\", NA),\n  y1 = runif(5, 0, 2),\n  y2 = runif(5, 0, 2),\n  y3 = runif(5, 0, 2),\n  z1 = runif(5, 0, 2),\n  z2 = runif(5, 0, 2),\n  z3 = runif(5, 0, 2)\n) |>\n  mutate(\n    across(matches(\"\\\\d\"), \\(x) if_else(x > 1, NA, round(x))),\n    across(everything(), as.character)\n    )\n\ngt(survey_data)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"utapxvmtle\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#utapxvmtle table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#utapxvmtle thead, #utapxvmtle tbody, #utapxvmtle tfoot, #utapxvmtle tr, #utapxvmtle td, #utapxvmtle th {\n  border-style: none;\n}\n\n#utapxvmtle p {\n  margin: 0;\n  padding: 0;\n}\n\n#utapxvmtle .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#utapxvmtle .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#utapxvmtle .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#utapxvmtle .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#utapxvmtle .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#utapxvmtle .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#utapxvmtle .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#utapxvmtle .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#utapxvmtle .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#utapxvmtle .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#utapxvmtle .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#utapxvmtle .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#utapxvmtle .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#utapxvmtle .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#utapxvmtle .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#utapxvmtle .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#utapxvmtle .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#utapxvmtle .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#utapxvmtle .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#utapxvmtle .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#utapxvmtle .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#utapxvmtle .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#utapxvmtle .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#utapxvmtle .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#utapxvmtle .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#utapxvmtle .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#utapxvmtle .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#utapxvmtle .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#utapxvmtle .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#utapxvmtle .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#utapxvmtle .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#utapxvmtle .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#utapxvmtle .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#utapxvmtle .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#utapxvmtle .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#utapxvmtle .gt_left {\n  text-align: left;\n}\n\n#utapxvmtle .gt_center {\n  text-align: center;\n}\n\n#utapxvmtle .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#utapxvmtle .gt_font_normal {\n  font-weight: normal;\n}\n\n#utapxvmtle .gt_font_bold {\n  font-weight: bold;\n}\n\n#utapxvmtle .gt_font_italic {\n  font-style: italic;\n}\n\n#utapxvmtle .gt_super {\n  font-size: 65%;\n}\n\n#utapxvmtle .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#utapxvmtle .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#utapxvmtle .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#utapxvmtle .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#utapxvmtle .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#utapxvmtle .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#utapxvmtle .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#utapxvmtle .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#utapxvmtle div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"id\">id</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"name_first\">name_first</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"name_last\">name_last</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"age\">age</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"x1\">x1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"x2\">x2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"x3\">x3</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"x_text\">x_text</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"y1\">y1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"y2\">y2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"y3\">y3</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"z1\">z1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"z2\">z2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"z3\">z3</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">1</td>\n<td headers=\"name_first\" class=\"gt_row gt_left\">Tom</td>\n<td headers=\"name_last\" class=\"gt_row gt_left\">Smith</td>\n<td headers=\"age\" class=\"gt_row gt_right\">62</td>\n<td headers=\"x1\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"x2\" class=\"gt_row gt_right\">1</td>\n<td headers=\"x3\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"x_text\" class=\"gt_row gt_left\">Lorem</td>\n<td headers=\"y1\" class=\"gt_row gt_right\">1</td>\n<td headers=\"y2\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"y3\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"z1\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"z2\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"z3\" class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">2</td>\n<td headers=\"name_first\" class=\"gt_row gt_left\">Penny</td>\n<td headers=\"name_last\" class=\"gt_row gt_left\">Jones</td>\n<td headers=\"age\" class=\"gt_row gt_right\">52</td>\n<td headers=\"x1\" class=\"gt_row gt_right\">0</td>\n<td headers=\"x2\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"x3\" class=\"gt_row gt_right\">1</td>\n<td headers=\"x_text\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"y1\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"y2\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"y3\" class=\"gt_row gt_right\">1</td>\n<td headers=\"z1\" class=\"gt_row gt_right\">0</td>\n<td headers=\"z2\" class=\"gt_row gt_right\">1</td>\n<td headers=\"z3\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">3</td>\n<td headers=\"name_first\" class=\"gt_row gt_left\">Trevor</td>\n<td headers=\"name_last\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"age\" class=\"gt_row gt_right\">37</td>\n<td headers=\"x1\" class=\"gt_row gt_right\">1</td>\n<td headers=\"x2\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"x3\" class=\"gt_row gt_right\">0</td>\n<td headers=\"x_text\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"y1\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"y2\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"y3\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"z1\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"z2\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"z3\" class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">4</td>\n<td headers=\"name_first\" class=\"gt_row gt_left\">Ursula</td>\n<td headers=\"name_last\" class=\"gt_row gt_left\">Smith</td>\n<td headers=\"age\" class=\"gt_row gt_right\">44</td>\n<td headers=\"x1\" class=\"gt_row gt_right\">1</td>\n<td headers=\"x2\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"x3\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"x_text\" class=\"gt_row gt_left\">Lorem</td>\n<td headers=\"y1\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"y2\" class=\"gt_row gt_right\">1</td>\n<td headers=\"y3\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"z1\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"z2\" class=\"gt_row gt_right\">1</td>\n<td headers=\"z3\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">5</td>\n<td headers=\"name_first\" class=\"gt_row gt_left\">Jenny</td>\n<td headers=\"name_last\" class=\"gt_row gt_left\">Jones</td>\n<td headers=\"age\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"x1\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"x2\" class=\"gt_row gt_right\">0</td>\n<td headers=\"x3\" class=\"gt_row gt_right\">1</td>\n<td headers=\"x_text\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"y1\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"y2\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"y3\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"z1\" class=\"gt_row gt_right\">1</td>\n<td headers=\"z2\" class=\"gt_row gt_right\">0</td>\n<td headers=\"z3\" class=\"gt_row gt_right\">NA</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nIn this example, we've got the data in a tabular format with responses as rows and variables as columns. There's an ID, the respondent's names and age, then three sets of questions:\n\n-   The `x1` to `x_text` questions are all part of the `x` group of questions\n-   The `y1` to `y3` and `z1` to `z3` questions are all part of the `y` and `z` group of questions, respectively\n\nLooking at this data, we can see that:\n\n-   Tom didn't answer any of the `z` questions\n-   Penny and Ursula have valid responses for at least one question from each group\n-   Trevor didn't give his last name and stopped responding after the `x` questions\n-   Jenny didn't respond to the `y` questions but answered at least one `z` question\n\n## A dictionary\n\nLike any good dataset, a data dictionary is available:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndictionary <- tibble(\n  variable = names(survey_data),\n  type = c(\"numeric\",rep(\"string\",2),\"numeric\",rep(\"factor\",3),\"string\",rep(\"factor\",6)),\n  variable_group = c(\"id\", \"name\", \"name\", \"age\", rep(\"x\", 4), rep(\"y\", 3), rep(\"z\", 3))\n)\n\ngt(dictionary)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"irjtnphjbz\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#irjtnphjbz table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#irjtnphjbz thead, #irjtnphjbz tbody, #irjtnphjbz tfoot, #irjtnphjbz tr, #irjtnphjbz td, #irjtnphjbz th {\n  border-style: none;\n}\n\n#irjtnphjbz p {\n  margin: 0;\n  padding: 0;\n}\n\n#irjtnphjbz .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#irjtnphjbz .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#irjtnphjbz .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#irjtnphjbz .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#irjtnphjbz .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#irjtnphjbz .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#irjtnphjbz .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#irjtnphjbz .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#irjtnphjbz .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#irjtnphjbz .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#irjtnphjbz .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#irjtnphjbz .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#irjtnphjbz .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#irjtnphjbz .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#irjtnphjbz .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#irjtnphjbz .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#irjtnphjbz .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#irjtnphjbz .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#irjtnphjbz .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#irjtnphjbz .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#irjtnphjbz .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#irjtnphjbz .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#irjtnphjbz .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#irjtnphjbz .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#irjtnphjbz .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#irjtnphjbz .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#irjtnphjbz .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#irjtnphjbz .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#irjtnphjbz .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#irjtnphjbz .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#irjtnphjbz .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#irjtnphjbz .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#irjtnphjbz .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#irjtnphjbz .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#irjtnphjbz .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#irjtnphjbz .gt_left {\n  text-align: left;\n}\n\n#irjtnphjbz .gt_center {\n  text-align: center;\n}\n\n#irjtnphjbz .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#irjtnphjbz .gt_font_normal {\n  font-weight: normal;\n}\n\n#irjtnphjbz .gt_font_bold {\n  font-weight: bold;\n}\n\n#irjtnphjbz .gt_font_italic {\n  font-style: italic;\n}\n\n#irjtnphjbz .gt_super {\n  font-size: 65%;\n}\n\n#irjtnphjbz .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#irjtnphjbz .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#irjtnphjbz .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#irjtnphjbz .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#irjtnphjbz .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#irjtnphjbz .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#irjtnphjbz .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#irjtnphjbz .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#irjtnphjbz div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"type\">type</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable_group\">variable_group</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">id</td>\n<td headers=\"type\" class=\"gt_row gt_left\">numeric</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">id</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">name_first</td>\n<td headers=\"type\" class=\"gt_row gt_left\">string</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">name</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">name_last</td>\n<td headers=\"type\" class=\"gt_row gt_left\">string</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">name</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">age</td>\n<td headers=\"type\" class=\"gt_row gt_left\">numeric</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">age</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">x1</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">x</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">x2</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">x</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">x3</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">x</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">x_text</td>\n<td headers=\"type\" class=\"gt_row gt_left\">string</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">x</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">y1</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">y</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">y2</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">y</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">y3</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">y</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">z1</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">z</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">z2</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">z</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">z3</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">z</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nIt's rudimentary but will serve its purpose to illustrate how we can use it in data cleaning and the reason for why I opted for a row-wise solution.\n\n## My solution\n\nThe column-wise solution for identifying the drop-offs is fairly straightforward, but I wasn't sure how to incorporate missingness at the question group level where the participant had not dropped off (e.g. Jenny). Maybe I'm too tidyverse-pilled, but I found it much easier to solve this problem using `group_by()`.\n\nTo start with, we need to transpose the data such that participant responses are in columns and the variables are in rows.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvey_data_tranposed <- survey_data |>\n  select(any_of(dictionary$variable)) |> \n  t() |> # <1>\n  as.data.frame() |> # <2>\n  rownames_to_column(var = \"variable\") # <3>\n\ngt(survey_data_tranposed)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"kvkzvmqdbt\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#kvkzvmqdbt table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#kvkzvmqdbt thead, #kvkzvmqdbt tbody, #kvkzvmqdbt tfoot, #kvkzvmqdbt tr, #kvkzvmqdbt td, #kvkzvmqdbt th {\n  border-style: none;\n}\n\n#kvkzvmqdbt p {\n  margin: 0;\n  padding: 0;\n}\n\n#kvkzvmqdbt .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#kvkzvmqdbt .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#kvkzvmqdbt .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#kvkzvmqdbt .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#kvkzvmqdbt .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kvkzvmqdbt .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kvkzvmqdbt .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kvkzvmqdbt .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#kvkzvmqdbt .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#kvkzvmqdbt .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#kvkzvmqdbt .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#kvkzvmqdbt .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#kvkzvmqdbt .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#kvkzvmqdbt .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#kvkzvmqdbt .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#kvkzvmqdbt .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#kvkzvmqdbt .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#kvkzvmqdbt .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#kvkzvmqdbt .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kvkzvmqdbt .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#kvkzvmqdbt .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#kvkzvmqdbt .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#kvkzvmqdbt .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kvkzvmqdbt .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#kvkzvmqdbt .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#kvkzvmqdbt .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kvkzvmqdbt .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kvkzvmqdbt .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#kvkzvmqdbt .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kvkzvmqdbt .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#kvkzvmqdbt .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kvkzvmqdbt .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kvkzvmqdbt .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kvkzvmqdbt .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kvkzvmqdbt .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kvkzvmqdbt .gt_left {\n  text-align: left;\n}\n\n#kvkzvmqdbt .gt_center {\n  text-align: center;\n}\n\n#kvkzvmqdbt .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#kvkzvmqdbt .gt_font_normal {\n  font-weight: normal;\n}\n\n#kvkzvmqdbt .gt_font_bold {\n  font-weight: bold;\n}\n\n#kvkzvmqdbt .gt_font_italic {\n  font-style: italic;\n}\n\n#kvkzvmqdbt .gt_super {\n  font-size: 65%;\n}\n\n#kvkzvmqdbt .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#kvkzvmqdbt .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#kvkzvmqdbt .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#kvkzvmqdbt .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#kvkzvmqdbt .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#kvkzvmqdbt .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#kvkzvmqdbt .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#kvkzvmqdbt .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#kvkzvmqdbt div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"V1\">V1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"V2\">V2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"V3\">V3</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"V4\">V4</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"V5\">V5</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">id</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">2</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">3</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">4</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">5</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">name_first</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">Tom</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">Penny</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">Trevor</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">Ursula</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">Jenny</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">name_last</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">Smith</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">Jones</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">Smith</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">Jones</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">age</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">62</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">52</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">37</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">44</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">NA</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">x1</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">NA</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">x2</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">0</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">x3</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">1</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">x_text</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">Lorem</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">Lorem</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">NA</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">y1</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">NA</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">y2</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">NA</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">y3</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">NA</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">z1</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">1</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">z2</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">0</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">z3</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">NA</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n1. `t()` transposes the data into a matrix\n2. Convert it back into a data frame\n3. Then take the row names (which were previously column names) and turn them into the `variable` column.\n\nNow that the data's in this format, we can join information from the dictionary\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvey_data_tranposed <- survey_data_tranposed |>\n  left_join(dictionary, by = \"variable\") |>\n  relocate(c(variable_group,type), .after = variable)\n\ngt(survey_data_tranposed)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"cqwwuxehtj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#cqwwuxehtj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#cqwwuxehtj thead, #cqwwuxehtj tbody, #cqwwuxehtj tfoot, #cqwwuxehtj tr, #cqwwuxehtj td, #cqwwuxehtj th {\n  border-style: none;\n}\n\n#cqwwuxehtj p {\n  margin: 0;\n  padding: 0;\n}\n\n#cqwwuxehtj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#cqwwuxehtj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#cqwwuxehtj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#cqwwuxehtj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#cqwwuxehtj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#cqwwuxehtj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cqwwuxehtj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#cqwwuxehtj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#cqwwuxehtj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#cqwwuxehtj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#cqwwuxehtj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#cqwwuxehtj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#cqwwuxehtj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#cqwwuxehtj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#cqwwuxehtj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#cqwwuxehtj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#cqwwuxehtj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#cqwwuxehtj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#cqwwuxehtj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cqwwuxehtj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#cqwwuxehtj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#cqwwuxehtj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#cqwwuxehtj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cqwwuxehtj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#cqwwuxehtj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#cqwwuxehtj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cqwwuxehtj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cqwwuxehtj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#cqwwuxehtj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cqwwuxehtj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#cqwwuxehtj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cqwwuxehtj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#cqwwuxehtj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cqwwuxehtj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#cqwwuxehtj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cqwwuxehtj .gt_left {\n  text-align: left;\n}\n\n#cqwwuxehtj .gt_center {\n  text-align: center;\n}\n\n#cqwwuxehtj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#cqwwuxehtj .gt_font_normal {\n  font-weight: normal;\n}\n\n#cqwwuxehtj .gt_font_bold {\n  font-weight: bold;\n}\n\n#cqwwuxehtj .gt_font_italic {\n  font-style: italic;\n}\n\n#cqwwuxehtj .gt_super {\n  font-size: 65%;\n}\n\n#cqwwuxehtj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#cqwwuxehtj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#cqwwuxehtj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#cqwwuxehtj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#cqwwuxehtj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#cqwwuxehtj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#cqwwuxehtj .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#cqwwuxehtj .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#cqwwuxehtj div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable_group\">variable_group</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"type\">type</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"V1\">V1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"V2\">V2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"V3\">V3</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"V4\">V4</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"V5\">V5</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">id</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">id</td>\n<td headers=\"type\" class=\"gt_row gt_left\">numeric</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">2</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">3</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">4</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">5</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">name_first</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">name</td>\n<td headers=\"type\" class=\"gt_row gt_left\">string</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">Tom</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">Penny</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">Trevor</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">Ursula</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">Jenny</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">name_last</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">name</td>\n<td headers=\"type\" class=\"gt_row gt_left\">string</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">Smith</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">Jones</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">Smith</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">Jones</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">age</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">age</td>\n<td headers=\"type\" class=\"gt_row gt_left\">numeric</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">62</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">52</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">37</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">44</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">NA</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">x1</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">x</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">NA</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">x2</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">x</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">0</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">x3</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">x</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">1</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">x_text</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">x</td>\n<td headers=\"type\" class=\"gt_row gt_left\">string</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">Lorem</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">Lorem</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">NA</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">y1</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">y</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">NA</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">y2</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">y</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">NA</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">y3</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">y</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">NA</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">z1</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">z</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">1</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">z2</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">z</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">0</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">z3</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">z</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">NA</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nThen I wrote the following function, which incorporates the information we just joined in how missingness categories are identified. The code annotations below the code chunk explain each step.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncode_missingness <- function(data, column) {\n  output <- data |>\n    mutate(drop_off = row_number() > max(which(!is.na(!!sym(column))))) |> # <1>\n    group_by(variable_group) |>\n    mutate(\n      drop_off = min(drop_off),  # <2>\n      n_vars = max(row_number()), # <3>\n      n_missing = sum(is.na(!!sym(column))),  # <3>\n      missingness = case_when( # <4>\n        drop_off == TRUE ~ \"-777777\", # <5>\n        n_vars > 1 & n_missing == n_vars ~ \"-888888\", # <6>\n        n_missing != n_vars & # <7>\n          is.na(!!sym(column)) & # <7>\n          type == \"factor\" ~ \"0\", # <7>\n        is.na(!!sym(column)) ~ \"-999999\", # <8>\n        .default = !!sym(column) # <9>\n      )\n    ) |> \n    ungroup() |> \n    select(missingness) |> \n    rename(!!sym(column) := missingness) |> # <10>\n    as.vector()\n  \n  return(output)\n}\n```\n:::\n\n\n1. For each row in the column, `!is.na()` returns `TRUE` (1) is non-missing or `FALSE` (0) if missing. `which()` then returns a vector of indices where the non-missing values are. `max()` then identifies the last row where non-missing data exists. Up to and including this row, `drop_off` is `FALSE`, becoming `TRUE` for every row thereafter.\n2. We then need to update `drop_off` if there are any non-missing responses within the question group. I'll explain why later, but the group minimum of `drop_off` will set all rows to `FALSE` if any `FALSE` exists.\n3. Then the number of variables within a group `n_vars` and number of missing responses within a group `n_missing` are calculated\n4. With these elements now created, we can use `case_when()` to apply the missing coding\n5. Due to step 2, we can be confident that `drop_off == TRUE` correctly identifies where responses have dropped off\n6. The value `-888888` identifies missingness at the question group level. If the number of missing responses within the question group is equal to the number of questions within said group, that is missing at the question group-level. `n_vars > 1` is included since I consider groups to mean a collection of 2 or more questions.\n7. In this condition, any missing values `is.na(!!sym(column))` for a factor question `type == \"factor\"` where there are non-missing values within the question group `n_missing != n_vars` are coded to 0\n8. Any remaining missing values can be coded as plain old `-999999`\n9. Any rows that didn't meet any of these rules are left as-is\n10. Finally, rename the `missingness` column to whatever the current value of the column input is, since we're going to iterate over every column\n\nNow that this function is defined, we can apply it to the relevant columns of the data, which are currently named `V1` through `V5`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresponses <- names(survey_data_tranposed |> select(matches(\"V\\\\d\")))\n\n# Use purrr:map to iterate over the columns identified in `responses`\nsurvey_data_coded <- map(responses, \\(x) code_missingness(survey_data_tranposed, x)) |>\n  bind_cols()\n\nsurvey_data_tranposed |>\n  bind_cols(survey_data_coded |>\n              rename_with( ~ paste0(., \"_new\"), matches(\"V\\\\d\"))) |> \n  select(variable, variable_group, type, starts_with(c(\"V1\",\"V2\",\"V3\",\"V4\",\"V5\"))) |> \n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ahaptoalnd\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ahaptoalnd table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ahaptoalnd thead, #ahaptoalnd tbody, #ahaptoalnd tfoot, #ahaptoalnd tr, #ahaptoalnd td, #ahaptoalnd th {\n  border-style: none;\n}\n\n#ahaptoalnd p {\n  margin: 0;\n  padding: 0;\n}\n\n#ahaptoalnd .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ahaptoalnd .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ahaptoalnd .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ahaptoalnd .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ahaptoalnd .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ahaptoalnd .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ahaptoalnd .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ahaptoalnd .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ahaptoalnd .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ahaptoalnd .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ahaptoalnd .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ahaptoalnd .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ahaptoalnd .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ahaptoalnd .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ahaptoalnd .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ahaptoalnd .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ahaptoalnd .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ahaptoalnd .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ahaptoalnd .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ahaptoalnd .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ahaptoalnd .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ahaptoalnd .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ahaptoalnd .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ahaptoalnd .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ahaptoalnd .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ahaptoalnd .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ahaptoalnd .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ahaptoalnd .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ahaptoalnd .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ahaptoalnd .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ahaptoalnd .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ahaptoalnd .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ahaptoalnd .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ahaptoalnd .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ahaptoalnd .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ahaptoalnd .gt_left {\n  text-align: left;\n}\n\n#ahaptoalnd .gt_center {\n  text-align: center;\n}\n\n#ahaptoalnd .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ahaptoalnd .gt_font_normal {\n  font-weight: normal;\n}\n\n#ahaptoalnd .gt_font_bold {\n  font-weight: bold;\n}\n\n#ahaptoalnd .gt_font_italic {\n  font-style: italic;\n}\n\n#ahaptoalnd .gt_super {\n  font-size: 65%;\n}\n\n#ahaptoalnd .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ahaptoalnd .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ahaptoalnd .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ahaptoalnd .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ahaptoalnd .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ahaptoalnd .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ahaptoalnd .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ahaptoalnd .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ahaptoalnd div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable_group\">variable_group</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"type\">type</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"V1\">V1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"V1_new\">V1_new</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"V2\">V2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"V2_new\">V2_new</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"V3\">V3</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"V3_new\">V3_new</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"V4\">V4</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"V4_new\">V4_new</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"V5\">V5</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"V5_new\">V5_new</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">id</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">id</td>\n<td headers=\"type\" class=\"gt_row gt_left\">numeric</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V1_new\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">2</td>\n<td headers=\"V2_new\" class=\"gt_row gt_left\">2</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">3</td>\n<td headers=\"V3_new\" class=\"gt_row gt_left\">3</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">4</td>\n<td headers=\"V4_new\" class=\"gt_row gt_left\">4</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">5</td>\n<td headers=\"V5_new\" class=\"gt_row gt_left\">5</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">name_first</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">name</td>\n<td headers=\"type\" class=\"gt_row gt_left\">string</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">Tom</td>\n<td headers=\"V1_new\" class=\"gt_row gt_left\">Tom</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">Penny</td>\n<td headers=\"V2_new\" class=\"gt_row gt_left\">Penny</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">Trevor</td>\n<td headers=\"V3_new\" class=\"gt_row gt_left\">Trevor</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">Ursula</td>\n<td headers=\"V4_new\" class=\"gt_row gt_left\">Ursula</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">Jenny</td>\n<td headers=\"V5_new\" class=\"gt_row gt_left\">Jenny</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">name_last</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">name</td>\n<td headers=\"type\" class=\"gt_row gt_left\">string</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">Smith</td>\n<td headers=\"V1_new\" class=\"gt_row gt_left\">Smith</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">Jones</td>\n<td headers=\"V2_new\" class=\"gt_row gt_left\">Jones</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V3_new\" class=\"gt_row gt_left\">-999999</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">Smith</td>\n<td headers=\"V4_new\" class=\"gt_row gt_left\">Smith</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">Jones</td>\n<td headers=\"V5_new\" class=\"gt_row gt_left\">Jones</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">age</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">age</td>\n<td headers=\"type\" class=\"gt_row gt_left\">numeric</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">62</td>\n<td headers=\"V1_new\" class=\"gt_row gt_left\">62</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">52</td>\n<td headers=\"V2_new\" class=\"gt_row gt_left\">52</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">37</td>\n<td headers=\"V3_new\" class=\"gt_row gt_left\">37</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">44</td>\n<td headers=\"V4_new\" class=\"gt_row gt_left\">44</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V5_new\" class=\"gt_row gt_left\">-999999</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">x1</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">x</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V1_new\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V2_new\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V3_new\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V4_new\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V5_new\" class=\"gt_row gt_left\">0</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">x2</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">x</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V1_new\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V2_new\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V3_new\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V4_new\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V5_new\" class=\"gt_row gt_left\">0</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">x3</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">x</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V1_new\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V2_new\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V3_new\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V4_new\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V5_new\" class=\"gt_row gt_left\">1</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">x_text</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">x</td>\n<td headers=\"type\" class=\"gt_row gt_left\">string</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">Lorem</td>\n<td headers=\"V1_new\" class=\"gt_row gt_left\">Lorem</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V2_new\" class=\"gt_row gt_left\">-999999</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V3_new\" class=\"gt_row gt_left\">-999999</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">Lorem</td>\n<td headers=\"V4_new\" class=\"gt_row gt_left\">Lorem</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V5_new\" class=\"gt_row gt_left\">-999999</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">y1</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">y</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V1_new\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V2_new\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V3_new\" class=\"gt_row gt_left\">-777777</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V4_new\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V5_new\" class=\"gt_row gt_left\">-888888</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">y2</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">y</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V1_new\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V2_new\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V3_new\" class=\"gt_row gt_left\">-777777</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V4_new\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V5_new\" class=\"gt_row gt_left\">-888888</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">y3</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">y</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V1_new\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V2_new\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V3_new\" class=\"gt_row gt_left\">-777777</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V4_new\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V5_new\" class=\"gt_row gt_left\">-888888</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">z1</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">z</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V1_new\" class=\"gt_row gt_left\">-777777</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V2_new\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V3_new\" class=\"gt_row gt_left\">-777777</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V4_new\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V5_new\" class=\"gt_row gt_left\">1</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">z2</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">z</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V1_new\" class=\"gt_row gt_left\">-777777</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V2_new\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V3_new\" class=\"gt_row gt_left\">-777777</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V4_new\" class=\"gt_row gt_left\">1</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V5_new\" class=\"gt_row gt_left\">0</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">z3</td>\n<td headers=\"variable_group\" class=\"gt_row gt_left\">z</td>\n<td headers=\"type\" class=\"gt_row gt_left\">factor</td>\n<td headers=\"V1\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V1_new\" class=\"gt_row gt_left\">-777777</td>\n<td headers=\"V2\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V2_new\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V3\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V3_new\" class=\"gt_row gt_left\">-777777</td>\n<td headers=\"V4\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V4_new\" class=\"gt_row gt_left\">0</td>\n<td headers=\"V5\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"V5_new\" class=\"gt_row gt_left\">0</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nIt looks to have done the job I intended it to do:\n\n-   Trevor has `-999999` for last name and the `x` text variable, and `-777777` from questions `y` onward\n-   Jenny has group-level missingness `-888888` for the `y` questions, because she goes on to answer the `z` questions so has not dropped off\n-   Missing responses to factor questions in a group are coded to `0` when a non-missing response exists on any other question\n\n## Some explanations\n\nThe reason why I update the value of `drop_off` after grouping (annotation 2) is because of the underlying structure of the data I'm working with, which isn't quite reflected in the example data. When outputting checkboxes, REDCap (a survey platform) auto-populates unchecked boxes with a `0` as opposed to missing. To work around this in the context of missingness, I first replace every `0` for these checkbox variables with `NA` so that I'm left with only values of `1` or `NA`. You might be thinking \"someone could reasonably have answered the question by not ticking any boxes\", except that we provide 'no' and 'unsure' checkboxes to reasonably cover all response options. So if these options are 0 in addition to the other options, I feel more confident in saying the whole question group was skipped.\n\nThe original reason for asking the question was about performance, and this approach is probably slower than a column-wise solution. It takes around 10 minutes to iterate over ~6,500 responses to ~550 variables across ~100 question groups. In the future this isn't going to be an issue because the data cleaning is going to be run on a frequent basis as data comes in (so smaller batches), rather than the entire set of responses.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}